import json
import re
import httpx
from pydantic import BaseModel, ValidationError
from typing import List, Dict, Any, Optional
from app.core.logging import get_logger

logger = get_logger(__name__)

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "gemma4:latest"

class EligibilitySchema(BaseModel):
    status: str
    text: str

class AnalyzeResponseSchema(BaseModel):
    explanation: str
    eligibility: EligibilitySchema
    checklist: List[str]
    missing_documents: List[str]
    # session_id is added in the endpoint, not generated by LLM

async def call_gemma_json(prompt: str, max_retries: int = 2) -> Dict[str, Any]:
    """
    Calls Gemma 4 local Ollama instance and expects a JSON response matching AnalyzeResponseSchema.
    Includes a repair pass and retries.
    """
    
    full_prompt = (
        f"{prompt}\n\n"
        "You MUST output valid JSON. No markdown formatting block (like ```json), no preamble, no trailing text. "
        "Just the raw JSON object matching this schema:\n"
        "{\n"
        '  "explanation": "string",\n'
        '  "eligibility": {"status": "likely|action-needed|confirmed", "text": "string"},\n'
        '  "checklist": ["string", "string"],\n'
        '  "missing_documents": ["string", "string"]\n'
        "}\n"
    )
    
    async with httpx.AsyncClient(timeout=120.0) as client:
        for attempt in range(max_retries + 1):
            try:
                response = await client.post(
                    OLLAMA_URL,
                    json={
                        "model": MODEL_NAME,
                        "prompt": full_prompt,
                        "stream": False,
                        "format": "json" # Ollama strict JSON format mode
                    }
                )
                response.raise_for_status()
                result_text = response.json().get("response", "")
                
                # Attempt to parse and validate
                parsed = _repair_and_parse_json(result_text)
                
                # Validate against schema
                AnalyzeResponseSchema(**parsed)
                return parsed
                
            except (json.JSONDecodeError, ValidationError) as e:
                logger.warning(f"Gemma JSON parse/validation failed on attempt {attempt+1}: {e}\nRaw output: {result_text[:200]}...")
                if attempt == max_retries:
                    logger.error("Max retries reached for Gemma JSON generation.")
                    raise RuntimeError("Failed to generate valid JSON from Gemma.")
                # Give it another try
                continue
            except Exception as e:
                logger.error(f"Error communicating with Ollama: {e}")
                raise

async def call_gemma_chat(history: List[Dict[str, str]], new_message: str) -> str:
    """
    Basic conversational call carrying previous context.
    We format the history into a prompt since /api/generate doesn't take standard chat history like OpenAI,
    unless we use /api/chat. We will use /api/chat.
    """
    
    messages = []
    for msg in history:
        messages.append({"role": msg["role"], "content": msg["content"]})
    
    messages.append({"role": "user", "content": new_message})

    async with httpx.AsyncClient(timeout=120.0) as client:
        try:
            response = await client.post(
                "http://localhost:11434/api/chat",
                json={
                    "model": MODEL_NAME,
                    "messages": messages,
                    "stream": False
                }
            )
            response.raise_for_status()
            return response.json().get("message", {}).get("content", "")
        except Exception as e:
            logger.error(f"Error communicating with Ollama Chat API: {e}")
            raise

def _repair_and_parse_json(text: str) -> Dict[str, Any]:
    # Try direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    
    # Try finding JSON block in markdown
    match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass
            
    # Try finding the first '{' and last '}'
    start = text.find('{')
    end = text.rfind('}')
    if start != -1 and end != -1 and end > start:
        try:
            return json.loads(text[start:end+1])
        except json.JSONDecodeError:
            pass
            
    raise json.JSONDecodeError("Could not repair JSON", text, 0)
